backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "_data/home.yml"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Instrument (Primary Language)"
            name: "instrument-lang-primary"
            widget: "string"
          - label: "Instrument (Secondary Language)"
            name: "instrument-lang-secondary"
            widget: "string"
          - label: "Quote (Primary Language)"
            name: "quote-lang-primary"
            widget: "text"
          - label: "Quote (Secondary Language)"
            name: "quote-lang-secondary"
            widget: "text"
          - label: "Concerts (Primary Language)"
            name: "concertsLangPrimary"
            widget: "string"
          - label: "Concerts (Secondary Language)"
            name: "concertsLangSecondary"
            widget: "string"
          - label: "Archive (Primary Language)"
            name: "archiveLangPrimary"
            widget: "string"
          - label: "Archive (Secondary Language)"
            name: "archiveLangSecondary"
            widget: "string"
      - file: "_data/calendar.yml"
        label: "Calendar"
        name: "calendar"
        fields:
          - label: "Quote (Secondary Language)"
            name: "quote-lang-secondary"
            widget: "text"
          - label: "Concerts (Primary Language)"
            name: "concertsLangPrimary"
            widget: "string"
          - label: "Concerts (Secondary Language)"
            name: "concertsLangSecondary"
            widget: "string"
          - label: "Archive (Primary Language)"
            name: "archiveLangPrimary"
            widget: "string"
          - label: "Archive (Secondary Language)"
            name: "archiveLangSecondary"
            widget: "string"
  - name: concerts
    label: Concerts
    label_singular: "Concert"
    folder: "concerts"
    create: true
    slug: "{{date | date('YYYY-MM-DD')}}-{{hallLangPrimary | slugify}}"
    summary: "{{date | date('D-M-YYYY')}}, {{hallLangPrimary}}"
    fields:
      - label: Tags
        name: tags
        widget: hidden
        default: concerts
      - label: City (Primary Language)
        name: cityLangPrimary
        widget: string
      - label: City (Secondary Language)
        name: cityLangSecondary
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Time
        name: time
        widget: string
        required: false
      - label: Hall (Primary Language)
        name: hallLangPrimary
        widget: string
      - label: Hall (Secondary Language)
        name: hallLangSecondary
        widget: string
      - label: Program (Primary Language)
        name: programLangPrimary
        widget: text
      - label: Program (Secondary Language)
        name: programLangSecondary
        widget: text
      - label: Musicians (Primary Language)
        name: musiciansLangPrimary
        widget: text
      - label: Musicians (Secondary Language)
        name: musiciansLangSecondary
        widget: text
      - label: Link
        name: link
        widget: string
      - file: "_data/contact.yml"
        label: "Contact Information"
        fields:
          - label: "Title"
            name: "title"
            widget: "object"
            fields:
              - label: "English"
                name: "en"
                widget: "string"
              - label: "German"
                name: "de"
                widget: "string"
          - label: "Email"
            name: "email"
            widget: "object"
            fields:
              - label: "English"
                name: "en"
                widget: "string"
              - label: "German"
                name: "de"
                widget: "string"
          - label: "Photographers"
            name: "photographers"
            widget: "object"
            fields:
              - label: "English"
                name: "en"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Alias"
                    name: "alias"
                    widget: "string"
                    required: false
              - label: "German"
                name: "de"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Alias"
                    name: "alias"
                    widget: "string"
                    required: false
              - label: "Web Design"
                name: "webDesign"
                widget: "object"
                fields:
                  - label: "English"
                    name: "en"
                    widget: "string"
                  - label: "German"
                    name: "de"
                    widget: "string"
