backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "_data/home.yml"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Background image"
            name: backgroundImage
            widget: "image"
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Instrument (Primary Language)"
            name: "instrumentLangPrimary"
            widget: "string"
          - label: "Instrument (Secondary Language)"
            name: "instrumentLangSecondary"
            widget: "string"
          - label: "Quote (Primary Language)"
            name: "quoteLangPrimary"
            widget: "text"
          - label: "Quote (Secondary Language)"
            name: "quoteLangSecondary"
            widget: "text"
          - label: "YouTube ID"
            name: "youTubeID"
            widget: "string"
            required: false
          - label: "Show Next Concert"
            name: "showNextConcert"
            widget: "boolean"
            default: true
          - label: "Next Concert Title (Primary Language)"
            name: "nextConcertLangPrimary"
            widget: "string"
          - label: "Next Concert Title (Secondary Language)"
            name: "nextConcertLangSecondary"
            widget: "string"
          - label: "Show Introduction"
            name: "showIntroduction"
            widget: "boolean"
            default: true
          - label: "Introduction Text (Primary Language)"
            name: "introductionLangPrimary"
            widget: "text"
            required: false
          - label: "Introduction Text (Secondary Language)"
            name: "introductionLangSecondary"
            widget: "text"
            required: false

      - file: "_data/bio.yml"
        label: "Biography"
        name: "bio"
        fields:
          - label: "Background image"
            name: backgroundImage
            widget: "image"
          - label: "Title (Primary Language)"
            name: "titleLangPrimary"
            widget: "string"
          - label: "Title (Secondary Language)"
            name: "titleLangSecondary"
            widget: "string"
          - label: "Bio (Primary Language)"
            name: "bioLangPrimary"
            widget: "markdown"
          - label: "Bio (Secondary Language)"
            name: "bioLangSecondary"
            widget: "markdown"
      - file: "_data/calendar.yml"
        label: "Calendar"
        name: "calendar"
        fields:
          - label: "Background image"
            name: backgroundImage
            widget: "image"
          - label: "Concerts (Primary Language)"
            name: "concertsLangPrimary"
            widget: "string"
          - label: "Concerts (Secondary Language)"
            name: "concertsLangSecondary"
            widget: "string"
          - label: "Archive (Primary Language)"
            name: "archiveLangPrimary"
            widget: "string"
          - label: "Archive (Secondary Language)"
            name: "archiveLangSecondary"
            widget: "string"
      - name: "media"
        label: "Media"
        file: "_data/media.yml"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            summary: "{{fields.alt}}"
            fields:
              - label: "Image Source"
                name: "src"
                widget: "image"
              - label: "Photographer"
                name: "photographer"
                widget: "string"
              - label: "Alt Text"
                name: "alt"
                widget: "string"
          - label: "Videos"
            name: "videos"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "YouTube ID"
                name: "youTubeID"
                widget: "string"
      - file: "_data/contact.yml"
        name: "Contact"
        label: "Contact Information"
        fields:
          - label: "Background image"
            name: backgroundImage
            widget: "image"
          - label: "Title (Primary Language)"
            name: "titleLangPrimary"
            widget: "string"
          - label: "Title (Secondary Language)"
            name: "titleLangSecondary"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Photographers (Primary Language)"
            name: "photographersLangPrimary"
            widget: "string"
          - label: "Photographers (Secondary Language)"
            name: "photographersLangSecondary"
            widget: "string"
          - label: "Photographers"
            name: "photographers"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
          - label: "Web Design"
            name: "webDesign"
            widget: "string"
          - label: "Web Designer (EN)"
            name: "webDesigner"
            widget: "string"
  - name: "concerts"
    label: "Concerts"
    folder: "concerts" # The folder containing your concert markdown files
    create: true
    slug: "{{date}}-{{hallLangPrimary | slugify}}"
    summary: "{{date | date('D.M.YYYY')}} - {{hallLangPrimary}}"
    fields:
      - label: Tags
        name: tags
        widget: hidden
        default: ["concerts"]
      - label: "City (Primary Language)"
        name: "cityLangPrimary"
        widget: "string"
      - label: "City (Secondary Language)"
        name: "cityLangSecondary"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm"
        format: "YYYY-MM-DDTHH:mm:ssZ"
      - label: "Hall (Primary Language)"
        name: "hallLangPrimary"
        widget: "string"
      - label: "Hall (Secondary Language)"
        name: "hallLangSecondary"
        widget: "string"
      - label: "Program (Primary Language)"
        name: "programLangPrimary"
        widget: "text"
      - label: "Program (Secondary Language)"
        name: "programLangSecondary"
        widget: "text"
      - label: "Musicians (Primary Language)"
        name: "musiciansLangPrimary"
        widget: "text"
      - label: "Musicians (Secondary Language)"
        name: "musiciansLangSecondary"
        widget: "text"
      - label: "Link"
        name: "link"
        widget: "string"
  - name: "settings"
    label: "Settings"
    files:
      - name: "colors"
        label: "Colors"
        file: "_data/settings.yml"
        fields:
          - label: "Primary Color"
            name: "colorPrimary"
            widget: "color"
          - label: "Secondary Color"
            name: "colorSecondary"
            widget: "color"
          - label: "Background Color"
            name: "colorBackground"
            widget: "color"
      - name: "template"
        label: "Templates"
        file: "_data/settings.yml"
        fields:
          - label: "Template"
            name: "template"
            widget: "select"
            options:
              - "elegant"
              - "simple"
            default: "elegant"
