backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "_data/home.yml"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Instrument (Primary Language)"
            name: "instrument-lang-primary"
            widget: "string"
          - label: "Instrument (Secondary Language)"
            name: "instrument-lang-secondary"
            widget: "string"
          - label: "Quote (Primary Language)"
            name: "quote-lang-primary"
            widget: "text"
          - label: "Quote (Secondary Language)"
            name: "quote-lang-secondary"
            widget: "text"
          - label: "Concerts (Primary Language)"
            name: "concertsLangPrimary"
            widget: "string"
          - label: "Concerts (Secondary Language)"
            name: "concertsLangSecondary"
            widget: "string"
          - label: "Archive (Primary Language)"
            name: "archiveLangPrimary"
            widget: "string"
          - label: "Archive (Secondary Language)"
            name: "archiveLangSecondary"
            widget: "string"
      - file: "_data/calendar.yml"
        label: "Calendar"
        name: "calendar"
        fields:
          - label: "Quote (Secondary Language)"
            name: "quote-lang-secondary"
            widget: "text"
          - label: "Concerts (Primary Language)"
            name: "concertsLangPrimary"
            widget: "string"
          - label: "Concerts (Secondary Language)"
            name: "concertsLangSecondary"
            widget: "string"
          - label: "Archive (Primary Language)"
            name: "archiveLangPrimary"
            widget: "string"
          - label: "Archive (Secondary Language)"
            name: "archiveLangSecondary"
            widget: "string"
      # - file: "_data/contact.yml"
      #   name: "Contact"
      #   label: "Contact Information"
      #   fields:
      #     - label: "Title"
      #       name: "title"
      #       widget: "object"
      #       fields:
      #         - label: "English"
      #           name: "en"
      #           widget: "string"
      #         - label: "German"
      #           name: "de"
      #           widget: "string"
      #     - label: "Email"
      #       name: "email"
      #       widget: "object"
      #       fields:
      #         - label: "English"
      #           name: "en"
      #           widget: "string"
      #         - label: "German"
      #           name: "de"
      #           widget: "string"
      #     - label: "Photographers"
      #       name: "photographers"
      #       widget: "object"
      #       fields:
      #         - label: "English"
      #           name: "en"
      #           widget: "list"
      #           fields:
      #             - label: "Name"
      #               name: "name"
      #               widget: "string"
      #             - label: "Alias"
      #               name: "alias"
      #               widget: "string"
      #               required: false
      #         - label: "German"
      #           name: "de"
      #           widget: "list"
      #           fields:
      #             - label: "Name"
      #               name: "name"
      #               widget: "string"
      #             # - label: "Alias"
      #             #   name: "alias"
