backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "_data/home.yml"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Instrument (Primary Language)"
            name: "instrument-lang-primary"
            widget: "string"
          - label: "Instrument (Secondary Language)"
            name: "instrument-lang-secondary"
            widget: "string"
          - label: "Quote (Primary Language)"
            name: "quote-lang-primary"
            widget: "text"
          - label: "Quote (Secondary Language)"
            name: "quote-lang-secondary"
            widget: "text"
      - file: "_data/bio.yml"
        label: "Biography"
        name: "bio"
        fields:
          - label: "Title (Primary Language)"
            name: "titleLangPrimary"
            widget: "string"
          - label: "Title (Secondary Language)"
            name: "titleLangSecondary"
            widget: "string"
          - label: "Bio (Primary Language)"
            name: "bioLangPrimary"
            widget: "markdown"
          - label: "Bio (Secondary Language)"
            name: "bioLangSecondary"
            widget: "markdown"
      - file: "_data/calendar.yml"
        label: "Calendar"
        name: "calendar"
        fields:
          - label: "Quote (Secondary Language)"
            name: "quote-lang-secondary"
            widget: "text"
          - label: "Concerts (Primary Language)"
            name: "concertsLangPrimary"
            widget: "string"
          - label: "Concerts (Secondary Language)"
            name: "concertsLangSecondary"
            widget: "string"
          - label: "Archive (Primary Language)"
            name: "archiveLangPrimary"
            widget: "string"
          - label: "Archive (Secondary Language)"
            name: "archiveLangSecondary"
            widget: "string"
      - name: "media"
        label: "Media"
        file: "_data/media.yml"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - label: "Image Source"
                name: "src"
                widget: "image"
              - label: "Photographer"
                name: "photographer"
                widget: "string"
              - label: "Alt Text"
                name: "alt"
                widget: "string"
      - file: "_data/contact.yml"
        name: "Contact"
        label: "Contact Information"
        fields:
          - label: "Title (Primary Language)"
            name: "titlePrimaryLanguage"
            widget: "string"
          - label: "Title (Secondary Language)"
            name: "titleSecondaryLanguage"
            widget: "string"
          - label: "Email"
            name: "email"
            widget: "string"
          - label: "Photographers (Primary Language)"
            name: "photographersPrimaryLanguage"
            widget: "string"
          - label: "Photographers (Secondary Language)"
            name: "photographersSecondaryLanguage"
            widget: "string"
          - label: "Photographers"
            name: "photographers"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
          - label: "Web Design"
            name: "webDesign"
            widget: "string"
          - label: "Web Designer (EN)"
            name: "webDesigner"
            widget: "string"
